# Generated by Django 3.2.8 on 2021-10-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyandmessage',
            name='key',
            field=models.IntegerField(verbose_name=range(10000000, 100000000)),
        ),
    ]
