# Generated by Django 3.2.8 on 2021-10-29 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgserver', '0003_alter_keyandmessage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyandmessage',
            name='key',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]${8}')]),
        ),
    ]
